name: extension
description: Package including lot helpers for easy developing on dart language
version: 0.0.3
author: Serge Shkurko <sergeshkurko@outlook.com>
homepage: https://github.com/rbcprolabs/dart_plugins/tree/master/packages/extension

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.5.3
