name: extension
description: Package including lot helpers for easy developing on dart language
version: 0.1.0
homepage: https://github.com/rbcprolabs/dart_plugins/tree/master/packages/extension

environment:
  sdk: '>=2.6.0 <3.0.0'

dev_dependencies:
  test: ^1.5.3
