name: universal_file
description: Cross-platform File & Directory that works in all platforms (browsers, Flutter, and VM)
repository: https://github.com/rbcprolabs/packages.dart/tree/master/packages/universal_file
issue_tracker: https://github.com/rbcprolabs/packages.dart/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+universal_file%22
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  pedantic: ^1.11.0
  test: ^1.16.0